version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "{ROOT 비밀번호}"
      MYSQL_DATABASE: "{DATABASE 이름}"
      MYSQL_USER: "{사용자 ID}"
      MYSQL_PASSWORD: "{비밀번호}"
    volumes:
      - ./volumes/data:/var/lib/mysql